#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        01_get_grid_details.yml 
# Author:       Adrian Bronder
# Date:         2020-06-23
# Description:  Get GRID information
#               with Ansible and REST APIs
#
# Modules:      URI (calling GRID REST APIs)
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://<GRID Admin>/grid/apidocs.html
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input_grid: &input_grid
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ auth_response.json.data }}"
      validate_certs:          false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "username":            "{{ SG_ADMIN_USER }}",
        "password":            "{{ SG_ADMIN_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: auth_response

  - name: Get Info from Grid
    netapp.storagegrid.na_sg_grid_info:
      gather_subset:
        - grid_health_topology_info
        - grid_config_product_version_info
      <<: *input_grid
    register: grid_info_results

  - name: Print GRID details
    debug:
      msg:
        - "Name:               {{ grid_info_results.sg_info['grid/health/topology'].data.name }}"
        - "Version:            {{ grid_info_results.sg_info['grid/config/product-version'].data.productVersion }}"

  - name: Print GRID nodes
    debug:
      msg:
        - "Data Center:        {{ item.0.name }}"
        - "Node Name:          {{ item.1.name }}"
        - "Node Type:          {{ item.1.type }}"
    with_subelements:
      - "{{ grid_info_results.sg_info['grid/health/topology'].data.children }}"
      - children
    loop_control:
      label: "{{ item.0.name }} - {{ item.1.name }}"
