#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        21_create_tenant.yml 
# Author:       Adrian Bronder
# Date:         2020-06-18
# Description:  Create a tenant on StorageGRID cluster
#               with Ansible modules
#
# Modules:      nac_sg_grid_account
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://galaxy.ansible.com/netapp/storagegrid
#
# Built-in help:
# ansible-doc netapp.storagegrid.nac_sg_grid_account
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input_grid: &input_grid
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ grid_auth_response.json.data }}"
      validate_certs:          false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "username":            "{{ SG_ADMIN_USER }}",
        "password":            "{{ SG_ADMIN_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: grid_auth_response

  - name: Create GRID tenant
    netapp.storagegrid.na_sg_grid_account:
      state:                   present
      name:                    "{{ TENANT }}"
      protocol:                s3
      management:              true
      use_own_identity_source: true
      allow_platform_services: true
      password:                "{{ TENANT_ROOT_PASS }}"
      update_password:         on_create
      quota_size:              "{{ (DEFAULT_QUOTA | int ) * ( 1000 | pow(3) ) | int }}"
      quota_size_unit:         bytes
      <<: *input_grid
    no_log: true
