#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        24_create_s3credentials.yml 
# Author:       Adrian Bronder
# Date:         2020-06-25
# Description:  Create S3 credentails for tenant user
#               with Ansible modules
#
# Modules:      nac_sg_org_user_s3_key
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://galaxy.ansible.com/netapp/storagegrid
#
# Built-in help:
# ansible-doc netapp.storagegrid.nac_sg_org_user_s3_key
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input_grid: &input_grid
      api_url:                     "https://{{ SG_ADMIN_NODE }}"
      auth_token:                  "{{ grid_auth_response.json.data }}"
      validate_certs:              false
    input_tenant: &input_tenant
      api_url:                     "https://{{ SG_ADMIN_NODE }}"
      auth_token:                  "{{ tenant_auth_response.json.data }}"
      validate_certs:              false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url:                         "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                      POST
      validate_certs:              false
      body_format:                 json
      body: {
        "username":                "{{ SG_ADMIN_USER }}",
        "password":                "{{ SG_ADMIN_PASS }}",
        "cookie":                  false,
        "csrfToken":               false
      }
    register: grid_auth_response

  - name: Get Grid Tenants
    netapp.storagegrid.na_sg_grid_info:
      gather_subset: grid_accounts_info
      <<: *input_grid
    register: grid_tenants

  - name: Get tenant by name
    set_fact:
      selected_tenant: "{{ grid_tenants.sg_info['grid/accounts'].data |
                        selectattr('name', 'equalto', TENANT) |
                        list }}"

  - name: Check for unique tenant
    fail:
      msg: "Unique tenant ID for given name '{{ TENANT }}' not found"
    when:
      ( selected_tenant | length ) != 1

  - name: Get tenant authorization token
    uri:
      url:                         "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                      POST
      validate_certs:              false
      body_format:                 json
      body: {
        "accountId":               "{{ selected_tenant.0.id }}",
        "username":                "root",
        "password":                "{{ TENANT_ROOT_PASS }}",
        "cookie":                  false,
        "csrfToken":               false
      }
    register: tenant_auth_response

  - name: Create S3 user credentials
    netapp.storagegrid.na_sg_org_user_s3_key:
      state:                       present
      unique_user_name:            "user/{{ TENANT }}-{{ TENANT_USER_NAME }}"
      <<: *input_tenant
    register: s3_cred

  - name: Check folder for storing credentials
    stat:
      path:                        ../cred_store
    register: s3cred_folder

  - name: Create directory if it does not exist
    file:
      path:                        ../cred_store
      state:                       directory
    when:
      not s3cred_folder.stat.exists

  - name: Write credentials to file
    copy:
      content:                     "{{ s3_cred.resp }}"
      dest:                        "../cred_store/{{ TENANT }}-{{ TENANT_USER_NAME }}"
