#!/usr/bin/env ansible-playbook

################################################################################
#
# Title:        41_create_hagroup.yml 
# Author:       Adrian Bronder
# Date:         2020-06-18
# Description:  Create a tenant on StorageGRID cluster
#               with Ansible modules
#
# Modules:      nac_sg_grid_account
#
# URLs:         https://docs.netapp.com/sgws-113/index.jsp
#               https://galaxy.ansible.com/netapp/storagegrid
#
# Built-in help:
# ansible-doc netapp.storagegrid.nac_sg_grid_account
#
################################################################################

- hosts: localhost
  gather_facts: false
  vars:
    input_grid: &input_grid
      api_url:                 "https://{{ SG_ADMIN_NODE }}"
      auth_token:              "{{ grid_auth_response.json.data }}"
      validate_certs:          false
  vars_files:
    - ../global.vars
  collections:
    - netapp.storagegrid

  tasks:
  - name: Get GRID authorization token
    uri:
      url:                     "https://{{ SG_ADMIN_NODE }}/api/v3/authorize"
      method:                  POST
      validate_certs:          false
      body_format:             json
      body: {
        "username":            "{{ SG_ADMIN_USER }}",
        "password":            "{{ SG_ADMIN_PASS }}",
        "cookie":              false,
        "csrfToken":           false
      }
    register: grid_auth_response

  - name: Create HA-Group
    netapp.storagegrid.na_sg_grid_ha_group:
      state:        present
      name:         "{{ HA_GROUP_NAME }}"
      description:  "{{ HA_GROUP_DESCRIPTION }}"
      gateway_cidr: "{{ HA_GATEWAY_CIDR }}"
      virtual_ips:  "{{ HA_GROUP_VIP }}"
      interfaces:   "{{ HA_GROUP_INTERFACES }}"
      <<: *input_grid
    register: create_hagroup_results
    #when: hagroup_exists is not defined

  - name: Create Load Balancer Endpoint
    netapp.storagegrid.na_sg_grid_gateway:
      state:  present
      display_name: "{{ ENDPOINT_NAME }}"
      port: "{{ ENDPOINT_PORT }}"
      secure: false
      enable_ipv4: true
      enable_ipv6: false
      <<: *input_grid
    register: create_endpoint_result

